/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import controller.ProjectController;
import controller.TaskController;
import java.util.Date;
import java.util.List;
//import java.util.List;
import model.Project;
import model.Task;

public class App {
    
    public static void main(String[] args) {
        
        /*TESTE HARDCODE DE CRUD DE PROJECT(NO BANCO DE DADOS)*/
        
        
       // ProjectController projectController = new ProjectController();
       // Project project = new Project();
       
       // project.setName("Projeto teste");
       // project.setDescription("Descrição");
       // projectController.save(project);
        
       
       // ProjectController projectController = new ProjectController();
       // Project project = new Project();
        
       // project.setId(2);
       // project.setName("Teste Projeto");
       // project.setDescription("Nova Descrição");
       // projectController.update(project);
        
       
       // ProjectController projectController = new ProjectController();
       
       // List<Project> projects = projectController.getAll();
       // System.out.println("Total de Projetos: " + projects.size());
       
       
       // ProjectController projectController  = new ProjectController();
        
       // projectController.removeById(1);
       
       /*---------------------------------------------------------------------*/
       
       /*TESTE HARDCODE DAS TASKS PERTENCENTE A UM PROJECT (NO BANCO DE DADOS)*/
       
       
      // TaskController taskController = new TaskController();
       
      // Task task = new Task();
       
      // task.setIdProject(2);
      // task.setName("Primeira Task");
      // task.setDescription("Descrição");
      // task.setNotes("Sem Notas");
      // task.setCompleted(false);
      // task.setDeadline(new Date());
      // taskController.save(task);
       
       
      // TaskController taskController = new TaskController();
       
      // Task task = new Task();
       
      // task.setId(1);
      // task.setIdProject(2);
      // task.setName("Primeira Task");
      // task.setDescription("Descrição");
      // task.setNotes("Sem Notas");
      // task.setCompleted(true);
      // task.setDeadline(new Date());
      // taskController.update(task);
      
       
      // TaskController taskController = new TaskController();
       
      // List<Task> tasks = taskController.getAll(2);
      // System.out.println("Total de Terefas: " + tasks.size());
      
      
      // TaskController taskController = new TaskController();
      
      // taskController.removeById(2);
             
    }    
}
